name: Create AWS Infra
on: 
    workflow_dispatch:
run-name: Create aws infra
jobs:
    create-infra:
        runs-on: ubuntu-latest
        permissions: 
            id-token: write
            contents: read
        steps: 
            - name: Configure aws
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with: 
                aws-region: us-east-1
                role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            - name: List files
              run: aws s3 ls
