name: Destroy AWS Infra
on: 
    workflow_dispatch:
run-name: Destroy aws infra
jobs:
    create-infra:
        runs-on: ubuntu-latest
        permissions: 
            id-token: write
            contents: read
        steps: 
            - name: Configure aws
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with: 
                aws-region: us-east-1
                role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.1"
            - name: Delete infra
              run: |
                cd iac
                terraform init
                terraform destroy -auto-approve
            - name: Delete image
              run: sh ./delete_image.sh